// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function MousePassthroughWithMove(ignore: boolean): $CancellablePromise<void> {
    return $Call.ByID(1913878022, ignore);
}

/**
 * SetWindowBorderless 设置指定窗口为无边框、无标题栏、无菜单
 */
export function SetWindowBorderless(hwnd: number): $CancellablePromise<boolean> {
    return $Call.ByID(2917959043, hwnd);
}
